### ISSUE TITLE
Stuck at fetching resource list: http://localhost:9000/docs/swagger.json; Please wait.

### ISSUE THREAD

**Issue by SangeetaGulia** [iheartradio/play-swagger#101]
I am a newbie to swagger and i am stuck after doing the following things on an error: 
I am using the following dependencies:

"com.iheart" %% "play-swagger" % "0.2.1-PLAY2.5",
"org.webjars" % "swagger-ui" % "2.1.4"

Following are the routes:
![image](https://cloud.githubusercontent.com/assets/17196401/17802393/b06e7f1a-660d-11e6-83af-fa56935c2b6e.png)

Following is the expected response type:
case class Output(response: JsValue)

This is the screenshot of where i am getting struck:

![image](https://cloud.githubusercontent.com/assets/17196401/17802377/a0d4a3f4-660d-11e6-88d5-33788c03a8cc.png)

This is what i get in the auto generated json file(where it gets struck with error : fetching resource list):

{"paths":{"/assets/{file}":{"get":{"tags":["routes"],"parameters":[{"name":"path","type":"string","required":true,"in":"query"},{"name":"file","type":"asset","required":true,"in":"path"}]}},"/docs/swagger.json":{"get":{"tags":["routes"],"summary":"swagger definition","description":"for swagger UI to consume"}},"/client/view":{"get":{"tags":["routes"],"responses":{"200":{"description":"success","schema":{"$ref":"#/definitions/models.Output"}}}}}},"definitions":{"models.Output":{"properties":{"response":{"type":"play.api.libs.json.jsvalue","required":true}},"required":["response"]}},"tags":[{"name":"routes"}]}

and this is my default swagger.json file(which i have created) : 
{
"swagger": "2.0",
"info": {
"version": "1.0.0",
"title": "Weather API",
"description": "A sample API that uses a Mashape weather API as an example to demonstrate features in the swagger-2.0 specification",
"termsOfService": "http://helloreverb.com/terms/",
"contact": {
"name": "Tom Johnson",
"email": "tomjohnson1492@gmail.com",
"url": "localhost:9000"
},
"license": {
"name": "MIT",
"url": "http://opensource.org/licenses/MIT"
}
},
"host": "localhost:9000",
"basePath" : "localhost:9000",
"schemes": [
"https"
],
"consumes": [
"application/json"
],
"produces": [
"application/text"
]
}

**Comment by kailuowang** [comment]
Hmm,  it's not obvious to me why you are getting that error from swagger ui. Do you want to click into that js error to see the code that throws the "cannot read property definitions of null"?

**Comment by SangeetaGulia** [comment]
Heres the js statements which is throwing this error :
![image](https://cloud.githubusercontent.com/assets/17196401/17809950/a6141a64-6637-11e6-99ca-029cd8efba0d.png)

Can you please share the controllers code which you have mentioned in the documentation: 
->  /api/cards    cards.Routes

It will be very helpful.

**Comment by kailuowang** [comment]
I can't tell from this code where the error "the property definitions of null" comes from
in your screenshot it was swagger-ui.js? 
The controller code doesn't matter (plus I don't have that code available). PlaySwagger doesn't try to parse controller.

**Comment by SangeetaGulia** [comment]
Yes the error is coming from swagger-ui.js. For more reference i have created a simple demo project to use swagger. Following is the link to the repository: 

https://github.com/SangeetaGulia/testSwagger

and i am getting the same error in this code too when i try to hit the url to get swagger-ui. 
Any help will be appreciated.

**Comment by kailuowang** [comment]
from your example, I noticed that you are using an old version of play swagger, would you mind update to the 0.4.0 first? No need for the PLAY2.5 suffix any more.

**Comment by SangeetaGulia** [comment]
Updated the version, but the same problem still persists :(
Anything else that i need to do???

**Comment by kailuowang** [comment]
Can you try with a minimum swagger base json? Keep only the required fields.

**Comment by kailuowang** [comment]
I am going to setup an example project in the next couple of days. If you can wait that might help too.

**Comment by SangeetaGulia** [comment]
In the demo project : https://github.com/SangeetaGulia/testSwagger (this is the same project whose link i have mentioned earlier),

I have used only : 
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Weather API",
    "description": "A sample API that uses a Mashape weather API as an example to demonstrate features in the swagger-2.0 specification",
  },
  "host": "localhost:9000",
  "basePath": "/docs",
  "schemes": [
    "https",
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ]
}
as minimum swagger base json.

Is there anything which i am missing???

**Comment by SangeetaGulia** [comment]
Actually i need to do it in next two days. You can use the demo project i have created, it may help me too to get the solution earlier. May be i am missing out something important.

**Comment by SangeetaGulia** [comment]
Hey, 
The error is resolved. After putting swagger.json into conf folder of the project the problem is resolved. 
Thanks for your help too.

I just want to ask one more question is there any way to configure on what can be the location to store swagger.json?

**Comment by kailuowang** [comment]
play-swagger reads swagger.json from resources. currently there is no way in play-swagger json to read from a location outside resources. I am glad that you resolved the issue. Thanks for the feedback!
