### ISSUE TITLE
Enhancement: Allow overriding basic type mappings

### ISSUE THREAD

**Issue by kbedel** [iheartradio/play-swagger#108]
I would like to be able to override the basic type mappings used in SwaggerParameterMapper. For example, I would like to use the standard swagger date-time format (RFC3339) for DateTime types rather than epoch. This would also be useful for #87 and maybe even #83 to allow overriding the mappings across the project, rather than having to override it on each usage.

If this approach fits with the overall goals of the project, I can try to work on this and contribute it back.

**Comment by kailuowang** [comment]
@kbedel sorry for the delayed response. I like that idea, I agree play-swagger needs such pluggable mapping logic.  Contribution will be greatly appreciated.
