### ISSUE TITLE
Hide QueryStringBindables

### ISSUE THREAD

**Issue by Uxio0** [iheartradio/play-swagger#109]
In our app we have some custom QueryStringBindables, for example one that transforms **limit** and **offset** _queryBinders_ to a **Pagination object.**

Problem is that swagger-play **autogenerates the Pagination object as a parameter**, which is invalid. How can I do to **hide it**?

Thanks for your work and help!

**Comment by kailuowang** [comment]
There is no way in current playswagger to hide it. 
cc @joprice (did you guys solve this problem? )
What feature do you think would solve this the best? I want to avoid the need of annotating the code, so I am thinking an "ignore" flag in the swagger comment for a parameter might be a good approach. Another approach might be allowing custom type-mapping logic like #108 suggested. 
What do you think?

**Comment by Uxio0** [comment]
Right now we are using the comments on the routes to add a description to these parameters like "ignore". I wouldn't mind to have an attribute to hide them.

```
#  parameters:
#     -  name: pag
#       required: false
#       description: Ignore this parameter, should be empty
```

Could be like

```
#  parameters:
#     -  name: pag
#       hidden: true
```

**Comment by kailuowang** [comment]
I like the hidden flag. added an feature issue.
