### ISSUE TITLE
Problem with package name that do not incluse 'controllers' word

### ISSUE THREAD

**Issue by krivopishind** [iheartradio/play-swagger#11]
Problem with package name that do not incluse 'controllers' word.
This mean if I have in my routes route like this, it will not work

POST     /calculation/order/calculate               	    com.marks.calculation.controller.CalculationController.calculate()

becouse you have strickly regexp in 
com/iheart/playSwagger/SwaggerSpecGenerator.scala (198:42)
"""(controllers[^\(]+)(\(.*\))?$"""
Please fix.

**Comment by kailuowang** [comment]
@krivopishind thanks for reporting the bug. Just fixed it and release 0.1.3 with this fix.
