### ISSUE TITLE
Sort Feature for swagger.json

### ISSUE THREAD

**Issue by jigyasu11** [iheartradio/play-swagger#118]
Is there a way to sort APIs ordering in swagger.json? swagger-ui has `sorter` but obviously it won't sort the json file. 

I am using Play-2.4 with Scala and generate swagger.json using controller method (as shown in the getting started example) so technically I can traverse the json and sort the paths object but it seems overkill to me :)
Is there a better way?

**Comment by kailuowang** [comment]
Unfortunately, as of now, there is no way to control the order other than the controller way you mentioned. A PR to add such functionality will be appreciated.

**Comment by jigyasu11** [comment]
Ah. Is it possible to configure `swagger-ui` webjar from swagger.yml? I tried but didn't work. Not sure if sorting Json is the right way because any presentation layer (like swagger-ui) can freely re-organize all the keys of json.

**Comment by tculshaw** [comment]
Swagger json now ordered as per routes file see #152. So this can be closed?
