### ISSUE TITLE
Allow override of defaultBase for runtime configurability

### ISSUE THREAD

**Issue by paulseddon** [iheartradio/play-swagger#131]
Ref version: v0.3.4-PLAY2.5

In `SwaggerSpecGenerator` the following method `private def defaultBase` returns a Play Json object. Could this method be made public so we can provide our own Json version of Swagger configuration? This allows runtime override of the config, so for example we can dynamically change the schemes depending on the protocol of the host app.

We can easily merge runtime config after loading swagger config into Json ourselves.

`val newConfig = config.map(c => c ++ Json.obj("schemes" -> "https"))`

**Comment by kailuowang** [comment]
@paulseddon you can merge runtime config after the whole swagger json is generated by the `SwaggerSpecGenerator`. Is that not going to work for you?
