### ISSUE TITLE
Null query parameter in route defined as "null" in spec

### ISSUE THREAD

**Issue by c100k** [iheartradio/play-swagger#132]
Hi, I have a route with an optional query parameter defined like this :

`GET /tasks controllers.TaskController.get(fields: String ?= null)`

When generating the spec :

```
{
    "in": "query",
    "name": "fields",
    "type": "string",
    "required": false,
    "default": "null",
}
```

it should be :

```
{
    "in": "query",
    "name": "fields",
    "type": "string",
    "required": false,
    "default": null,
}
```

or no `default` value at all. Is this a normal behavior ?

**Comment by kailuowang** [comment]
play-swagger doesn't understand the special word null, it deems it as a default string value, as if you wrote `fields: String ?= Dog` . To be honest with you, I think a better way might be `GET /tasks controllers.TaskController.get(fields: Option[String])`, play-swagger does understand `Option` and will treat that parameter as `required: false`
