### ISSUE TITLE
Can't find the plugin even i have added the resovler

### ISSUE THREAD

**Issue by levis2hsu** [iheartradio/play-swagger#133]
in the project/plugins.sbt i defined the resolver

resolvers += "iheart-sbt-plugin-releases" at  "https://dl.bintray.com/iheartradio/sbt-plugins"

addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.5.2-PLAY2.4")

However, when run the sbt compile, it still can't find com.iheart#play-swagger_2.10;0.5.2-PLAY2.4:

This is the error message:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.iheart#play-swagger_2.10;0.5.2-PLAY2.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.iheart:play-swagger_2.10:0.5.2-PLAY2.4 ((com.iheart.sbtPlaySwagger.SwaggerPlugin) SwaggerPlugin.scala#L28)

Anybody can help on this?

**Comment by kailuowang** [comment]
You shouldn't need to add the resolver. This should be available in the default resolves. Try make sure you are on the latest sbt?

**Comment by mikeumus** [comment]
Putting the path in `~/.sbt/repositories` that had a version for Scala 2.10 that worked with my sbt 0.13 worked for me:

```
[repositories]
local
iheart-sbt-plugin-releases: https://dl.bintray.com/iheartradio/sbt-plugins, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier] ).[ext]
iheart-play-swagger_2.11-releases: https://jcenter.bintray.com
```

and the `jcenter` version for `sbt publishLocal`
