### ISSUE TITLE
Adding description for request parameters

### ISSUE THREAD

**Issue by idoshamun** [iheartradio/play-swagger#142]
Is it possible to add description to the request parameters or the model properties?

**Comment by anaPerezGhiglia** [comment]
Hi! just saw this when facing the same need. I found the way to do it:
You can add description by adding the parameters section in the routes file

An example:
###
#  summary: Pet information
#  description: Retrives pet information from id
#  parameters:
#    - name: id
#      description: the pet id
#  responses:
#    200:
#      schema:
#         $ref: '#/definitions/model.Pet'
###
GET   /pet/:id/information   controllers.PetController.petFrom(id: String)

Notice that the parameter name in the documentation must be the same declared as a variable in the route definition

Hope it helps!

**Comment by kailuowang** [comment]
thanks @anaPerezGhiglia I took the liberty to edit your comment for better formating, hope you don't mind.

**Comment by idoshamun** [comment]
Thanks for the help!
