### ISSUE TITLE
 java.lang.NoSuchMethodError: com.iheart.playSwagger.SwaggerSpecGenerator

### ISSUE THREAD

**Issue by akhettar-zz** [iheartradio/play-swagger#144]
Hi

I am using swagger-plugin version 0.5.3 and getting the error below. Any idea?

Thanks

Ayache

ERROR
[success] created output: /Users/ayache/workspaces/homeoffice/rmp-caseworker/target
[info] Running com.iheart.playSwagger.SwaggerSpecRunner /Users/ayache/workspaces/homeoffice/rmp-caseworker/target/swagger/swagger.json routes uk.gov.homeoffice.ddat.rmp.caseworker.model
[error] (run-main-1) java.lang.NoSuchMethodError: com.iheart.playSwagger.SwaggerSpecGenerator.generate(Ljava/lang/String;)Lscala/util/Try;

**Comment by leszekgruchala** [comment]
Try in `build.sbt`:
```
dependencyOverrides := Set(
      "com.iheart" %% "play-swagger" % "0.5.4",
      "org.webjars" % "swagger-ui" % "2.2.10-1"
    )
```
