### ISSUE TITLE
Use environment variables in swagger.yml

### ISSUE THREAD

**Issue by kindlychung** [iheartradio/play-swagger#149]
Is it possible? If not is there a work around?

Specifically, I would like to do something like this:

```yaml
---
  swagger: "2.0"
  info:
    title: "API"
    description: "AR dev REST API"
    version: "1.0.0"
  host: ${API_HOST}
```

**Comment by kailuowang** [comment]
Here is a work around
https://github.com/iheartradio/play-swagger/blob/master/README.md#how-do-i-use-a-different-host-for-different-environment
It shouldn't be too hard to enhance play swagger to support your environment var idea. A PR would be much appreciated.

**Comment by mattdornfeld** [comment]
So is this possible now? I see there was a commit. This is the first link that comes up when googling. If someone could post a link to an example here that would be great.
