### ISSUE TITLE
endpoints in swagger should match order in routes file

### ISSUE THREAD

**Issue by tculshaw** [iheartradio/play-swagger#150]
Using version 0.5.4

Fantastic product:)

Now using it successfully across multiple routes files, BUT the one thing that's annoying is that the generator doesn't follow the ordering of endpoints in the routes file. This means I can't specify ordering for the swagger output, ie. it appears random. 

Any ideas how I can solve?

**Comment by kailuowang** [comment]
Unfortunately, this is not supported by play-swagger now. The iHeartRadio team has no plan to fix this. But we'll gladly review and merge a PR that does :)
 This is a dup of #34, if you don't mind I am going to close this one.
