### ISSUE TITLE
Provide json examples of a PUT method manually

### ISSUE THREAD

**Issue by kindlychung** [iheartradio/play-swagger#153]
Here is the code:

```
###
#  summary: Update the roles of a user.
#  security:
#    - Bearer: []
#  tags:
#    - User
#  parameters:
#    - name: body
#      schema:
#        $ref: '#/definitions/models.User'
#  responses:
#    200:
#      description: Update successful.
#    400:
#      description: Invalid input data or non-existant user
###
PUT           /user/:username                                controllers.UserController.update(username: String)
```

Right now I am letting swagger to generate json example according to the `User` model, but the `update` method actually is more flexible and accepts json objects following different models. So I would like to write up the examples manually. Is there a way to do this?

**Comment by kailuowang** [comment]
Whatever you write in the swagger comment will be carried over to the final swagger document. So to achieve something that isn't generated by play-swagger,  you just need to learn how to achieve it in native swagger json and write it in either the base swagger.yml or the swagger comment.

**Comment by kindlychung** [comment]
```
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "name"
  ],
  "example": {
    "name": "Puma",
    "id": 1
  }
}
```

An exmple listed above for future reference.
