### ISSUE TITLE
Parameter for output file name?

### ISSUE THREAD

**Issue by pnzrdrgoon** [iheartradio/play-swagger#155]
Is it possible to supply a parameter to allow for a different output filename rather than swagger.json?

**Comment by kailuowang** [comment]
in build.sbt
```scala
swaggerFileName := "yourname.json"
```

**Comment by pnzrdrgoon** [comment]
Awesome, thank you.  I must have missed that in the documentation.

**Comment by kailuowang** [comment]
@pnzrdrgoon it's not documented, as well as some other sbt setting keys. PR is more than welcome ;)
