### ISSUE TITLE
Alias names for Model definitions.

### ISSUE THREAD

**Issue by unrelentingfox** [iheartradio/play-swagger#165]
Is there a way to give my models an alias so they don't include the full package name?

For example: I would like to just show Contact, and Prospect.
![image](https://user-images.githubusercontent.com/19860874/27699881-031541d4-5cb9-11e7-821f-674d9e94b278.png)

**Comment by slaudat** [comment]
In your swagger base file you can do this: 
`---
openapi: 3.0.0
 info:
    title: "API"
    description: "REST API"
    version: "1.0.0"
  components:
    schemas:
      com.mealticket.prospecting.ProspectResource.Contact:
        title: "Contact"
`
then 'com.mealticket.prospecting.ProspectResource.Contact' will appear as 'Contact' in Swagger UI. There may be other ways to do it, but this works.

**Comment by mrwillis** [comment]
@slaudat that problem with this is that it's not dynamic. The generated file gets changed every time.

**Comment by Javakky-pxv** [comment]
#146
