### ISSUE TITLE
2 odd possible bugs

### ISSUE THREAD

**Issue by namco1992** [iheartradio/play-swagger#171]
Hi,

I am new to Play framework and Swagger and I thought this tool is amazing. However, there is something odd happens when I try to generate the docs.

1. The `swaggerDomainNameSpaces` does not work. I'm working on scala 2.11.8 and Play 2.5.10. My `build.sbt` like this:

```scala
swaggerDomainNameSpaces := Seq("beans", "models")
```

However, nothing works except `models`. I tried several times and no another namespace can be imported.

2. When I switch to `models` and test again, I found out that the field names cannot be extracted accurately. You can see that all the fields became x$1, x$2 and so on.

```yaml
  models.Pickup:
    properties:
      x$1:
        type: integer
        format: int64
      x$2:
        type: integer
        format: int64
      x$3:
        type: string
        enum:
          - SG
          - MY
          - ID
          - PH
          - TH
          - VN
          - MM
      x$4:
        $ref: '#/definitions/models.User'
      x$5:
        type: array
        items:
          $ref: '#/definitions/models.Order'
      x$6:
        $ref: '#/definitions/models.Pickup.Status'
    required:
      - x$1
      - x$2
      - x$3
      - x$4
      - x$5
      - x$6
```

I wonder if these are bugs and how can I fix it, thanks.

**Comment by kailuowang** [comment]
I think the DomainNamespaces looks like a bug, it could be that it only recognize the last item. 
As for the fields name, I haven't seen that before. Is your Pickup a case class?

**Comment by namco1992** [comment]
Hi,

Thank you for the prompt response. As for the first one, I think it could be another reason since I also tried just removed "models" and keep "beans" in the `swaggerDomainNameSpaces` but still no good.

I forgot to mention that I use the Play framework for Java, not scala, and `Pickup` is nothing but a normal Java class. Does play-swagger support Java as good as scala?

**Comment by kailuowang** [comment]
after changing sbt file, you would need a `reload` for that to take effect. 
Unfortunately, play-swagger doesn't support java that well yet.

**Comment by namco1992** [comment]
Hi,

As for the first issue, I reloaded the `build.sbt` but still no good, and I tried several times actually.

I assume the second issue is caused by the less support of Java. Will you consider to support Java in the near future?

**Comment by kailuowang** [comment]
maybe you have another duplicated setting down the file? Play-swagger doesn't have "models" as a default setting, so it must've been picked up somewhere. As for java support, I myself won't have time to work on it any time soon, but any contribution is more than welcome.

**Comment by namco1992** [comment]
Thanks for your time, I will check it out later. I'm not familiar with scala, therefore it could take a while to understand the code, maybe I will try if I have spare time. I will close the thread after I check the first issue tomorrow.

**Comment by namco1992** [comment]
Hi @kailuowang ,

I checked it again and I find out the settings were not effective when I used the command "swagger" which was generated by the `play-swagger`. The Domain namespaces worked when I ran the application directly.

**Comment by kailuowang** [comment]
That seems a bug. the "swagger" command should take that into effect.
