### ISSUE TITLE
Swagger UI is empty: Refused to execute inline script JavaScript error (Chrome, Play 2.6)

### ISSUE THREAD

**Issue by rocketpages** [iheartradio/play-swagger#174]
I am receiving the following JavaScript error while trying to browse to the Swagger UI at:

`http://localhost:9000/docs/swagger-ui/index.html?url=/assets/swagger.json`

The JavaScript error is as follows:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-VQJGzLUGVTxuS6MyxMPDzebQrR0g3EP5mtKIGdnnGxY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

The error is being thrown by the inline script starting on line 34 of `index.html`:

```javascript
  <script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      // etc ...
```

Please advise if this is a bug or a configuration issue.

**Comment by rocketpages** [comment]
The root cause is that in Play 2.6 a number of security headers are turned on by default. Out of the box a new implementation of Play 2.6 and Swagger UI will result in an empty UI page.

The immediate fix is to disable `contentSecurityPolicy` by setting to `null` in `application.conf`. 

```
# https://www.playframework.com/documentation/latest/Configuration
play.filters.headers.contentSecurityPolicy = null
```

It may potentially be worth calling out this security change in Play 2.6 in the Swagger docs. Many new Play projects begin with Swagger UI to explore an API definition, so I imagine others will bump up against this as well.

See https://www.playframework.com/documentation/2.6.x/SecurityHeaders for more details.

**Comment by kailuowang** [comment]
Thanks for reporting the issue and solution. if you are interested, a PR to update the FAQ with this notes will be really appreciated.

**Comment by bsylla** [comment]
Doesn't `play.filters.headers.contentSecurityPolicy = null` mean that you accept to load everything from everywhere ?
Something like `play.filters.headers.contentSecurityPolicy="default-src 'self'; script-src 'self' 'unsafe-inline'"` is less permissive and should work.
See [this interesting thread](https://stackoverflow.com/questions/30280370/how-does-content-security-policy-work)

**Comment by mattiharo** [comment]
I added the line:
play.filters.headers.contentSecurityPolicy=null
on my Spring Boot config file, which is added to my SwaggerConfig.java:
@PropertySource({"classpath:default.properties"})
public class SwaggerConfig {
...
}
Still get the same error. It's like the values in default.properties was never were never read.
Any ideas?

**Comment by richdougherty** [comment]
@mattiharo, `play.filters.headers.contentSecurityPolicy=null` is a setting for Play Framework, you'll need to do something else for Spring Boot.

It might be possible to set up Play 2.6 so it has more permissive headers for the Swagger UI but keeps restrictive settings for the rest of the site. See docs here: https://www.playframework.com/documentation/2.6.x/SecurityHeaders#Action-specific-overrides

In order to override headers for the Swagger UI you could use a custom Assets controller. E.g. 

https://github.com/richdougherty/play-swagger-csp-attempt/blob/38c247d989584ace3b0c0431aad415566378b2f5/conf/routes#L10

https://github.com/richdougherty/play-swagger-csp-attempt/blob/38c247d989584ace3b0c0431aad415566378b2f5/app/controllers/CspAssets.scala#L11-L27

Unfortunately there were quite a few CSP violations and I haven't worked through them. It's possible that the Swagger UI needs updating so that it supports CSP more easily. E.g. https://github.com/swagger-api/swagger-ui/issues/4187

**Comment by richdougherty** [comment]
@wsargent is working on an enhancement to the CSP API in Play. You guys might be interested in this, because it might make it possible to get play-swagger's swagger-ui code working with CSP.

https://github.com/playframework/playframework/pull/8242

**Comment by romeromfm** [comment]
> The root cause is that in Play 2.6 a number of security headers are turned on by default. Out of the box a new implementation of Play 2.6 and Swagger UI will result in an empty UI page.
> 
> The immediate fix is to disable `contentSecurityPolicy` by setting to `null` in `application.conf`.
> 
> ```
> # https://www.playframework.com/documentation/latest/Configuration
> play.filters.headers.contentSecurityPolicy = null
> ```
> It may potentially be worth calling out this security change in Play 2.6 in the Swagger docs. Many new Play projects begin with Swagger UI to explore an API definition, so I imagine others will bump up against this as well.
> 
> See https://www.playframework.com/documentation/2.6.x/SecurityHeaders for more details.

I struggled for days until I found this fix. You saved me! Thank you, @rocketpages 
My versions:
- Scala: 2.12.8
- SBT: 1.1.6
- Play: 2.6.21

**Comment by romeromfm** [comment]
@rocketpages and @bsylla, you saved my life. Thank you, guys.
