### ISSUE TITLE
$ref isn't recognized in Java Play!

### ISSUE THREAD

**Issue by yurir** [iheartradio/play-swagger#203]
I use play 2.6 with Java. Since there are no case classes in Java, how can i make Data Type in swagger to recognize body parameters?

**Comment by kailuowang** [comment]
thanks for reporting it. I just added an FAQ item to answer this question
https://github.com/iheartradio/play-swagger/blob/master/README.md#is-play-java-supported
Thanks

**Comment by yurir** [comment]
Sorry, but it didn't work.
This is the related route:
```
###
#  summary: Moves task to requested board
#  parameters:
#    - name: body
#      schema:
#        $ref: '#/definitions/api.tasks.MoveTaskToBoardRequest'
###
PUT        /tasks/board                  controllers.TaskController.moveTaskToBoard()
```

And here is the MoveTaskToBoardRequest:
```

package api.tasks;

public class MoveTaskToBoardRequest {
    private long taskId;
    private long boardId;

    public MoveTaskToBoardRequest(long taskId, long boardId) {
        this.taskId = taskId;
        this.boardId = boardId;
    }

    public long getTaskId() {
        return taskId;
    }

    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }

    public long getBoardId() {
        return boardId;
    }

    public void setBoardId(long boardId) {
        this.boardId = boardId;
    }
}



```

Am i doing something wrong?

Thanks

**Comment by yurir** [comment]
This is how it looks:
<img width="984" alt="screen shot 2017-12-19 at 21 49 35" src="https://user-images.githubusercontent.com/695168/34175884-92f9ff08-e506-11e7-946c-1135284968e4.png">

**Comment by kailuowang** [comment]
did you set `api` as your  `swaggerDomainNameSpace`?

**Comment by yurir** [comment]
Yes, you are right, it wasn't api, it was models, as in example. Now it looks better, but it still didn't recognize the param names, it puts x$1 and x$2 instead of the actual param names in both example and model:
<img width="978" alt="screen shot 2017-12-19 at 23 41 56" src="https://user-images.githubusercontent.com/695168/34180186-75e2dab0-e516-11e7-9400-d96389d7b190.png">

**Comment by yurir** [comment]
Another issue: Model tab shows that i have 
```
api.tasks.MoveTaskToBoardRequest {
  x$1 (integer),
  x$2 (integer)
}
```
but in code i have long

**Comment by kailuowang** [comment]
Unfortunately that's the best play-swagger can do for Play Java at the moment.

**Comment by yurir** [comment]
Ok, so i did it this way:

```
###
#  summary: Moves task to requested board
#  parameters:
#    - name: body
#      schema:
#        type: object
#        properties:
#          taskId:
#            type: long required
#          boardId:
#            type: long required
#        example:
#          taskId: 1
#          boardId: 1
###
PUT        /tasks/board                  controllers.TaskController.moveTaskToBoard()
```

Maybe it will help somebody

**Comment by yurir** [comment]
I'd like to try to add the support by self. Could you guide me how to do it for java?

**Comment by kailuowang** [comment]
@yurir thanks, I myself am not that familiar with Java reflection API either. I would imagine that for Java you would need to get the getter and setter methods and their field names.

**Comment by yurir** [comment]
@kailuowang
I am familiar with Java reflection, but I'd like to understand where should I call it. Where can I put my code that will use Java reflection to analyze the classes?

**Comment by yurir** [comment]
@kailuowang could you please guide me, how to achieve it?

**Comment by larousso** [comment]
Hi, 

I can make java generation work turning the `javacOptions in Compile ++= Seq("-parameters")` option on. 

This way the parameter names of the constructor are resolved during compilation. 

The constructor with all fields must be the first declared constructor if there are multiple constructors.

**Comment by nalreja** [comment]
> Hi,
> 
> @yurir I can make java generation work turning the `javacOptions in Compile ++= Seq("-parameters")` option on.
> 
> This way the parameter names of the constructor are resolved during compilation.
> 
> The constructor with all fields must be the first declared constructor if there are multiple constructors.

-parameters didn't really work. Any other hints?

**Comment by shubhamp-zeotap** [comment]
Hi, I am also using Java Play (2.6.x). Do we have any solution other than manually writing the spec in comments for that x$1, x$2 issue ? I wanted to use this library for Swagger docs. Looks awesome but I am stuck on this specific issue !? Any help appreciated.

Thanks,
