### ISSUE TITLE
### NoDocs ###

### ISSUE THREAD

**Issue by doncorsean** [iheartradio/play-swagger#208]
Right now a ### NoDocs ### line must be above every route where no documentation is desired. Any easy way to make this default? So no docs unless a doc block is detected?

**Comment by SoheilJafari** [comment]
Hi,
Could i add ### NoDocs ### top of the xxx.routes definition in main route file like below?
### NoDocs ###
->    /admin/             admin.Routes

**Comment by kailuowang** [comment]
No. That is not supported as of now. I think such a feature makes seems,
Maybe it's possible.

**Comment by Javakky-pxv** [comment]
@doncorsean @SoheilJafari 
The functionality to ignore all of the document has already been added. ( #491 )
We are also discussing a method to skip selectively within a specified range. ( #469 )
