### ISSUE TITLE
Class not found when mapping complex map

### ISSUE THREAD

**Issue by dmitriyvolk** [iheartradio/play-swagger#217]
Hi!
I'm getting the following error
```
scala.ScalaReflectionException: class my.domain.models.AThing] in JavaMirror with URLClassLoader with NativeCopyLoader with RawResources(
... <skipped a bunch of lines listing every classpath member> ...
not found
```

All this is while trying to create a definition for a case class which has a property of the following type:
```
weirdProperty: Map[Role, Seq[AThing]]
```
where `Role` is an enumeratum-based value, which serializes to a String, and `AThing` is defined as
```
case class AThing(name: String, id: Option[String])
```

After reading https://github.com/iheartradio/play-swagger/issues/204 I'm guessing I need to help the generator and provide a custom mapping for such a complex type, but all my attempts lead nowhere. This is my latest attempt:
```
  - type: scala\.collection\.immutable\.Map[my\.domain\.models\.Role, scala.collection\.immutable\.Seq[my\.domain\.models\.AThing]]
    specAsParameter: []
    specAsProperty:
      type: object
      properties:
        code:
          $ref: '#/definitions/my.domain.models.Role'
        text:
          type: array
          items:
            $ref: '#/definitions/my.domain.models.AThing'
```

I don't mind manually writing more mappings, but I need some pointers.

Thanks!

**Comment by kailuowang** [comment]
you might need to escape the `[` as well, since it's a regex .
