### ISSUE TITLE
Consider Case Classes in Dependency Module of same Project

### ISSUE THREAD

**Issue by lmserrano** [iheartradio/play-swagger#218]
In a multi-module sbt project is it possible to have the SwaggerPlugin configured in such a way that any case classes referenced in route files, but which are present in other non-play modules of the project, get properly resolved? If it is not possible, any thoughts regarding possibly having this functionality added at some point in the future?

**Comment by kailuowang** [comment]
have you tried? I believe it should work just fine.

**Comment by kailuowang** [comment]
'models' is supposed to be your root package name of your case class

**Comment by kailuowang** [comment]
I would move all settings inside the build.sbt files inside the modules to the  top build.sbt file. Not sure if the current settings creates the modules

**Comment by lmserrano** [comment]
Thank you. I've updated the configuration as you suggested, to a single build.sbt at root project level.

No swagger.json seems to be being generated (whether with swaggerTarget or not), and I'm getting the following error when accessing the Swagger UI:
Can't read swagger JSON from http://localhost:9000/assets/swagger.json

In any case, and in the event I don't have the chance to experiment more with it for now, has this use case ever been successfully achieved before in any configuration? I think the fact that I don't use play modules structure and am using sbt multi module in which just one of the modules is a Play one could be making things more difficult.
