### ISSUE TITLE
Enumeratum Types

### ISSUE THREAD

**Issue by benshaw** [iheartradio/play-swagger#224]
Im not sure if its a bug, missing feature or error on my side but currently Enumeratum types seem to be skipped by the generator.

https://github.com/lloydmeta/enumeratum

**Comment by BenShaw** [comment]
I have tried a custom type mapping that could be applied to all enumeratum types but have not been able to figure out a working format

**Comment by tilmanginzel** [comment]
Hi, #290 added partial support for Enumeratum. We noticed that it only works for `EnumEntry`, and not `ValueEnumEntry` types (e.g. `StringEnumEntry` or `IntEnumEntry`). 

The current implementation specifically looks for a method called `entryName` via reflection. Unfortunately, this method only exists for [`EnumEntry`](https://github.com/lloydmeta/enumeratum/blob/3beb3dd1fe22cda12fe13469c299af5a9c07aa33/enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala#L21). `ValueEnumEntry` has a method called [`value`](https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-core/src/main/scala/enumeratum/values/ValueEnumEntry.scala#L13) instead.

@gabfssilva @kailuowang Do you think it is reasonable to extend the current implementation to check first for `enumEntry`, and then for `value`? If that makes sense to you, I could try to provide a pull request for this. :)

**Comment by gabfssilva** [comment]
Seems fine to me. ;)

**Comment by kailuowang** [comment]
I would welcome a PR as well.
