### ISSUE TITLE
Responses not being picked up

### ISSUE THREAD

**Issue by BenShaw** [iheartradio/play-swagger#227]
ive used an example straight from the doc
```
###
#  summary: create a card
#  tags:
#    - Card Endpoints
#  responses:
#    200:
#      description: success
#      schema:
#        $ref: '#/definitions/v2.models.Communication'
###
GET     /v1/communication/:reportid v2.controllers.CommunicationController.get(reportid:Long)
```

However i get the following error when i try to view the doc

>> Schema error at paths['/v1/communication/{reportid}'].get
>> should have required property 'responses'
>> missingProperty: responses

And the generated JSON is 
```
"paths":{"/v1/communication/{reportid}":{"get":{"operationId":"get","tags":["routes"],"parameters":[{"in":"path","name":"reportid","type":"integer","format":"int64","required":true}]},
```

**Comment by BenShaw** [comment]
Happy to contribute via PR is you can point me in the right direction

**Comment by kailuowang** [comment]
hmmm, I wonder what if you remove the `tags: - Card Endpoints`. That's newly added to the readme doc, but now I am not sure if it works

**Comment by BenShaw** [comment]
ive tried removing both tags and summary to no success
it picks up the schema for body but thats it at the moment

**Comment by kailuowang** [comment]
from the json you posted, it didn't pickup the summary either?

**Comment by BenShaw** [comment]
Ok thanks !

I figured out the issue, your comment above made me realise that it wasnt seeing this endpoint at all
my complete routes file had a comment above the spec for this endpoint

```
# Communication Endpoints
###
#  summary: create a card
#  tags:
#    - Card Endpoints
#  responses:
#    200:
#      description: success
#      schema:
#        $ref: '#/definitions/v2.models.Communication'
###
GET     /v1/communication/:reportid v2.controllers.CommunicationController.get(reportid:Long)
```

This leading comment was causing the issue. After i remove it then the generator picks it up
Thanks for your quick feedback !
