### ISSUE TITLE
RequestBody not appearing in Spec

### ISSUE THREAD

**Issue by qbrent** [iheartradio/play-swagger#230]
I'm trying to set the requestBody

![selection_999 317](https://user-images.githubusercontent.com/24631535/47736874-8bccd800-dc67-11e8-96e1-2247540ed92f.png)

But in the spec; I'm only seeing

![selection_999 318](https://user-images.githubusercontent.com/24631535/47736923-a3a45c00-dc67-11e8-9068-8d089e56f4a3.png)

Project setup is:

addSbtPlugin("com.iheart" %% "sbt-play-swagger" % "0.7.4")
Play 2.6; Scala 2.12 and Sbt 1.2.6

Everything else is working great.

Any pointers much appreciated.
Thanks

**Comment by kailuowang** [comment]
not srue about the requestBody swagger spec, but the following should work
```
#  parameters:
#    - name: body
#      schema:
#        $ref: '#/definitions/com.iheart.Track'
```

**Comment by qbrent** [comment]
BRILLIANT

Thank you so much for the exceedingly rapid reply.
