### ISSUE TITLE
Add possibility to get formatted swagger.json file

### ISSUE THREAD

**Issue by feoktant** [iheartradio/play-swagger#231]
Currently swagger.json file is a pretty one liner.
For easier diff, as a developer I need to have formatted json file. It gives possibility to frontend guys diff changes in contract.

I suggest to add flag for pretty swagger doc printing into file. By default feature should be turned off

**Comment by kailuowang** [comment]
changes look fine to me. A PR would be great

**Comment by feoktant** [comment]
@kailuowang thanks! Here is PR: https://github.com/iheartradio/play-swagger/pull/232

**Comment by kailuowang** [comment]
fixed by #232
