### ISSUE TITLE
operationId is not unique

### ISSUE THREAD

**Issue by stereobooster** [iheartradio/play-swagger#237]
According to spec `operationId` must be unique

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. The operationId value is case-sensitive. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.
>
> [OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md)

But because we use name of the method it can be non-unique, like `create`, `list`, `remove` etc.

Maybe we can use concatenation of object name and method to form unique ids?

**Comment by henricook** [comment]
I'm working around this by putting `operationId` in my entries by hand where method names conflict
