### ISSUE TITLE
unable to resolve plugin 0.7.5 play 2.7

### ISSUE THREAD

**Issue by erezlevy** [iheartradio/play-swagger#244]
[warn] ==== bintray-iheartradio-maven: tried
[warn]   https://dl.bintray.com/iheartradio/maven/com/iheart/play-swagger_2.12_1.0/0.7.5-PLAY2.7/play-swagger-0.7.5-PLAY2.7.pom

for some reason it is looking for sbt version 1.0
play-swagger_2.12_1.0 => is play-swagger_2.12

**Comment by benikm91** [comment]
Older post. I had the same problem, found this question, then later I could fix it myself. Post answer if others are running into the same issue and find this question.

In plugins.sbt:
```sbt
resolvers += Resolver.url(
  "bintray-iheartradios-sbt-plugins",
  url("http://dl.bintray.com/iheartradio/sbt-plugins"))(
  Resolver.ivyStylePatterns)

addSbtPlugin("com.iheart" %% "sbt-play-swagger" % "0.7.5-PLAY2.7")
```

In build.sbt:

```sbt
lazy val root = (project in file(".")).enablePlugins(PlayScala, SwaggerPlugin)
```

**Comment by kailuowang** [comment]
Use 
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.7.5-PLAY2.7")

"%" instead of "%%"

**Comment by kailuowang** [comment]
Corrected in the readme.

**Comment by Mododo** [comment]
For sbt 1.x current setup in `plugins.sbt` is 
```
resolvers += Resolver.bintrayIvyRepo("iheartradio", "sbt-plugins/sbt-play-swagger")
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.9.1")
```
