### ISSUE TITLE
schemas not generated vor swaggerV3 := true

### ISSUE THREAD

**Issue by an-tex** [iheartradio/play-swagger#246]
Using ```swaggerV3 := false``` the definitions are correctly generated from the model and included in the swagger.json under the "definitions" key. 

But when I switch to ```swaggerV3 := true```, the swagger.json contains ```{"components":{"schemas":{}},....```, thus missing the same definitions.

I have no idea why, by the look of the source of `SwaggerSpecGenerator.scala` it seems the only difference for handling V3 is the different json key.

**Comment by jkgeyti** [comment]
Make sure you're using "#/components/schemas/" as a prefix rather than "#/definitions/". 

While this is an expected change in the swagger format between 2 and 3, I feel like it's worth a mention in the docs.

**Comment by an-tex** [comment]
Ahh thanks @jkgeyti ! That helped. Would deff be nice to mention that in the doc

**Comment by kailuowang** [comment]
Let's keep this open until it's added to the doc.

**Comment by an-tex** [comment]
@kailuowang of course sorry, I still had this tab opened and our replies clashed ;)

**Comment by an-tex** [comment]
omg it is actually mentioned in the Readme under V3... 🤭

> Also, for $ref fields you will want to prefix paths with #/components/schemas/ instead of #/definitions/

**Comment by jkgeyti** [comment]
It'd probably still be good to add an example to emphasise how to use $ref

**Comment by kailuowang** [comment]
thank you @jkgeyti

**Comment by BenShaw** [comment]
I have this same issue
I have followed the directions in the readme including using 

``` 
#      schema: 
 #        $ref: ' #/components/schemas/v1.models.Communication'
```
 but the generated swagger.json contains

``` "components":{"schemas":{}} ```

**Comment by kailuowang** [comment]
Did you set  `v1` as one of the  swaggerDomainNameSpaces ?

**Comment by BenShaw** [comment]
swaggerDomainNameSpaces := Seq("v1.models")
