### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by vasyl-zhurba** [iheartradio/play-swagger#257]
Please add support for Scala 2.13

**Comment by kailuowang** [comment]
are you using the sbt plugin? or the library directly?

**Comment by vasyl-zhurba** [comment]
Actually we are using both in different projects. We use library directly to make alterations in `swagger.json` output.

**Comment by kailuowang** [comment]
Released 0.7.7-PLAY2.7 on Scala 2.13

**Comment by vasyl-zhurba** [comment]
Thank you!

**Comment by vasyl-zhurba** [comment]
I'm not sure if i do it correctly, or sbt-play-swagger is published correctly.

> [warn] ==== bintray-iheartradio-sbt-plugins: tried
[warn]   https://dl.bintray.com/iheartradio/sbt-plugins/com/iheart/sbt-play-swagger_2.12_1.0/0.7.7-PLAY2.7/sbt-play-swagger-0.7.7-PLAY2.7.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.iheart#sbt-play-swagger;0.7.7-PLAY2.7: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.iheart:sbt-play-swagger:0.7.7-PLAY2.7 (scalaVersion=2.12, sbtVersion=1.0)

But real file resides under https://dl.bintray.com/iheartradio/sbt-plugins/com/iheart/sbt-play-swagger/0.7.7-PLAY2.7/ (missing `_2.12_1.0` part)

**Comment by kailuowang** [comment]
use 
```
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.7.7-PLAY2.7")`
``` 
instead of 
```
addSbtPlugin("com.iheart" %% "sbt-play-swagger" % "0.7.5-PLAY2.7")
```

**Comment by vasyl-zhurba** [comment]
Actually I used
```
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.7.7-PLAY2.7")
```
(with single `%`)

plugins.sbt
```
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.7.7-PLAY2.7")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.3")
resolvers += Resolver.bintrayRepo("iheartradio", "sbt-plugins")
```

sbt
```
[warn] ==== bintray-iheartradio-sbt-plugins: tried
[warn]   https://dl.bintray.com/iheartradio/sbt-plugins/com/iheart/sbt-play-swagger_2.12_1.0/0.7.7-PLAY2.7/sbt-play-swagger-0.7.7-PLAY2.7.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.iheart#sbt-play-swagger;0.7.7-PLAY2.7: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by kailuowang** [comment]
My bad. try `0.7.8-PLAY2.7` should be working now.

**Comment by vasyl-zhurba** [comment]
Thanks! It works now.
