### ISSUE TITLE
the branch strategy of this plugin

### ISSUE THREAD

**Issue by thirdteeth** [iheartradio/play-swagger#278]
Hi Team, 
I want to create a pull request to submit the following changes
1. add playJava to SwaggerPlugin
2. use the parameter to switch how to generate the definition properties
   true: use jackson introspect
   false: use default
3. upgrade snakeyaml to 1.2.4 and add typed parameter to load method
4. add mapper to java.time.* 
5. remove the play java request from generated parameters

The changes are only for play 2.7, please show me how to create the PR.

Thanks,
Damon Pu

**Comment by kailuowang** [comment]
The play 2.7 code is on the `play2.7` branch, please PR against that branch .
