### ISSUE TITLE
Hiding swagger request parameter when appending Request to Routes

### ISSUE THREAD

**Issue by nick123pig** [iheartradio/play-swagger#288]
As of Play 2.7, the play Http.Context is deprecated. They now recommend appending  `play.mvc.Http.Request` in the [routes file](https://www.playframework.com/documentation/2.7.x/JavaHttpContextMigration27#Http.Context.current()-and-Http.Context.request()-deprecated).

For example...`POST /foo controllers.FooController.foo(request: Request)`

However, this appends an undefined `request` in the swagger parameters (as shown in the image below)

![image](https://user-images.githubusercontent.com/5910005/66356141-309b6f00-e927-11e9-9698-e7bfbd2022eb.png)

Is there any support for hiding globally these `play.mvc.Http.Request` objects in the swagger definitions? Thank you!

**Comment by kailuowang** [comment]
Try this?
https://github.com/iheartradio/play-swagger/blob/master/README.md#how-to-override-type-mappings

**Comment by nick123pig** [comment]
I did try that, I should have mentioned that. It didn't do anything to the swagger output.

```---
  - type: play\.mvc\.Http\.Request
    specAsParameter: []```

**Comment by kailuowang** [comment]
how about write`play.mvc.Http.Request` also in your routes file?
