### ISSUE TITLE
Paths ordering

### ISSUE THREAD

**Issue by carlsonngo** [iheartradio/play-swagger#34]
Generated JSON paths is in reverse order compared to ones defined in routes file

**Comment by kailuowang** [comment]
@carlsonngo thanks for reporting, I am curious how important this order is to you?

**Comment by carlsonngo** [comment]
Feeding the data to swagger-ui will display the paths in the wrong order. This might be confusing for people if they want to preserve the order in the generated api docs.

**Comment by kailuowang** [comment]
@carlsonngo thanks for the context.

**Comment by slouc-bytecode** [comment]
+1 For me it's not even reverse order, but a completely random one. Using 0.2.0.

**Comment by andrewcbl** [comment]
+1 for me, it is displayed as random order. Using play 2.5.4, play-swagger 0.5.0

**Comment by tculshaw** [comment]
So how do we order, using play 2.5.x, play-swagger 0.5.3? Looks random to me.

**Comment by kailuowang** [comment]
@tculshaw we haven't implement the feature the preserve the ordering in the routes file. Any PR will be more than welcome :)

**Comment by tculshaw** [comment]
If any one is interested I have a partial solution, hence this isn't a formal pull request.

Replacing the path function in SwaggerSpecGenerator, I order the main unique paths as per the ROUTE file, but NOT the order where multiple methods (GET,PUT,POST,DELETE) apply to the same path. It's a lot better than it used to be, and will suffice for my needs, but still not quite 100%! 

private def paths(routes: Seq[Route], prefix: String, tag: Option[Tag]): JsObject = {
    JsObject {
      val endPointEntries = routes.flatMap(route => endPointEntry(route, prefix, tag))
      
      val zgbp = endPointEntries.zipWithIndex.groupBy(_._1._1)
      import collection.mutable.LinkedHashMap
      val lhm = LinkedHashMap(zgbp.toSeq sortBy (_._2.head._2): _*)
      val gbp2 = lhm mapValues (_ map (_._1)) toSeq
      
      gbp2.toSeq.map( x => (x._1,x._2.map(_._2).reduce(_ deepMerge _)))
    }
  }

I banged my head against the wall to get this going, so hope this is helpful to somebody!

**Comment by kailuowang** [comment]
Thanks very much @tculshaw, it's not quite 100% but it's still a step forward. I will appreciate it if you want to submit a PR (just need a simple test for the ordering).

**Comment by tculshaw** [comment]
This can now be closed? Thanks for accepting my change #152

**Comment by kailuowang** [comment]
@tculshaw it's still a partial solution right? ("NOT the order where multiple methods (GET,PUT,POST,DELETE) apply to the same path")

**Comment by tculshaw** [comment]
Yeah sorry!

I wasn't going to get totally caught up in the method orders where the path
is shared. It did my head in just doing this one;)

Probably(?) most users who want the ordering will be happy to have the
solution provided as is.

I will look at if I get chance - if you think it's worth doing?



Tony Culshaw MA Cantab
Director
Mentation Limited - Custom Software Development

**Comment by kailuowang** [comment]
I imagine it would be nice for some users, but I don't particularly have that need in my projects. Thanks for offering! And thanks again for your contribution!

**Comment by tculshaw** [comment]
No worries:)

Tony Culshaw MA Cantab
Director
Mentation Limited - Custom Software Development
