### ISSUE TITLE
play-swagger no longer available in mvnrepository

### ISSUE THREAD

**Issue by dannashirn** [iheartradio/play-swagger#341]
I just ran a build for a project which uses this dependency, and it's no longer present in maven repository.
https://repo1.maven.org/maven2/com/iheart/

**Comment by efasel** [comment]
It's not here at all: https://mvnrepository.com/search?q=sbt-play-swagger&d=com.iheart

And https://dl.bintray.com/sbt/sbt-plugin-releases/com.iheart/sbt-play-swagger/ contains no version for scala_2.13 but only:

- scala_2.10/
- scala_2.12/
