### ISSUE TITLE
Overriding the name/location of swagger.yml

### ISSUE THREAD

**Issue by arteme** [iheartradio/play-swagger#360]
It would be nice to be able to override location and name of the `swagger.yml` file directly from SBT. In my case, I'm trying to do preprocessing to generate parts of the file and I want to be able to specify my own file as the input to the swagger JSON generation.

**Comment by tilmanginzel** [comment]
Hi @arteme, is this what you are looking for?

```scala
// build.sbt

swaggerTarget := new File("path/to/swagger/location")
swaggerFileName := "customSwagger.json"
```
