### ISSUE TITLE
Switch from bintray to mnvrepository

### ISSUE THREAD

**Issue by DanGrigore** [iheartradio/play-swagger#365]
Very soon, bintray will come to an end. (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/?utm_source=mkto&utm_medium=email&utm_campaign=bintray-sunset&utm_content=global-02-2021)

In this case, it's possible to migrate the play-swagger repo to Maven Central?

**Comment by bradrust** [comment]
bintray has been sunsetted now so (from my perspective), there is no way to include this in my build.sbt.   Is there another approach to including a 0.10.3 artifact?

**Comment by kailuowang** [comment]
I don't have the time, but if anyone can copy relevant publish settings from https://github.com/iheartradio/ficus/blob/master/project/Publish.scala 
to this repo 
https://github.com/iheartradio/play-swagger/blob/master/project/Publish.scala
Then I can try release it to sonatype

**Comment by kailuowang** [comment]
published to maven central
