### ISSUE TITLE
reading from body, and recognizing the inputs?

### ISSUE THREAD

**Issue by Ciantic** [iheartradio/play-swagger#37]
I've marked my actions like this, so I can read the input variables from the JSON body of the request:

```
  private case class SignUpData(firstName: String, lastName: String, email: String, password: String)

  def signUp = Action.async(parse.json) { implicit request =>
    request.body.validate[SignUpData].map { data =>
        // ... Code of the action is here.
      }
    }.recoverTotal {
      case error =>
        Future.successful(BadRequest(Json.obj("error" -> Messages("invalid.data"))))
    }
  }
```

Naturally the automatic system within play-swagger can't understand anything about e.g. SignUpData. But how should I do this so that I can read the input variables from the body, and have play-swagger automatically recognize them?

It maybe that I'm using Play incorrectly also.

**Comment by kailuowang** [comment]
I have an example of the exact use case in the README
https://github.com/iheartradio/play-swagger#how-to-specify-body-content-in-a-post-endpoint
You need to expose your `SignUpData` as a public class in one of the domain packages you pass in to swagger's generator. See the domain package part in the code example here
https://github.com/iheartradio/play-swagger#step-2

**Comment by Ciantic** [comment]
Oh right, I have to define this for all. I must find a better way, because my whole API works by reading the input parameters from body. Marking each and all in the comment is not a good option.

Also of course private case class is not a good choice, but even as public, it won't recognize them automatically.

**Comment by Ciantic** [comment]
Maybe I have to do some JsonBodyAction that takes a type that can be validated, then teach the play-swagger to understand JsonBodyAction is automatically a body parser.

**Comment by kailuowang** [comment]
By design play-swagger avoid being coupled with controller implementations. If you think that adding that comment is too much work(to me it's like a javadoc return statement), then you might want to look at the annotation  approach here https://github.com/swagger-api/swagger-play. That lib reflects on your controllers to extract information.
