### ISSUE TITLE
Java option not working on play 2.8

### ISSUE THREAD

**Issue by GithubUser8080** [iheartradio/play-swagger#395]
Using scala 2.13 and play 2.8, the playJava := true option does not work, causing Java bean properties to show up as x$1, x$2 instead of their real names

**Comment by GithubUser8080** [comment]
It looks like change [this change ](https://github.com/iheartradio/play-swagger/commit/50376d9db5396d4933bd346c3c6c9587bce5a090#diff-6bbc5cec7c3e7db3b3bc75e467cdc62d4aca75b74045126a263aed3d06239d1aL165) removed the java parameter option from DefinitionGenerator construction

**Comment by kailuowang** [comment]
Ah, missed that during code review, a PR to fix it will be much appreciated.

**Comment by GithubUser8080** [comment]
PR submitted, thanks

**Comment by kailuowang** [comment]
released 0.10.6-PLAY2.8
