### ISSUE TITLE
Multiple routes with the same path, only one is shown

### ISSUE THREAD

**Issue by williamho** [iheartradio/play-swagger#4]
If multiple routes use the same path, docs are only generated for one of them

e.g.,
```
GET  /somepath
POST /somepath
```

**Comment by natefrechette** [comment]
I just discovered this as well.  Is there a fix for this? or anyway I can get around it for the time being?

**Comment by natefrechette** [comment]
It doesn't seem that this issue was resolved? I have multiple CRUD routes that operate on the same resource as follows:

GET /users/:id
PUT /users/:id
DELETE /users/:id

and the last one listed is the only path that shows up in the swagger documentation.

Thanks!

**Comment by williamho** [comment]
@natefrechette does this work for you? I was getting the same issue after pulling the latest changes, but it turns out my browser was just caching the old data -- doing a hard refresh seems to have fixed it.

**Comment by natefrechette** [comment]
Yes that is why I deleted the post.  Thank you! Seems once i deployed locally and reset my cache it worked for me as well
