### ISSUE TITLE
Publish the SBT plugin for Scala 2.13

### ISSUE THREAD

**Issue by denisftw** [iheartradio/play-swagger#405]
It seems that the plugin is not published for Scala 2.13. In Maven central I can only see this:

https://repo1.maven.org/maven2/com/iheart/sbt-play-swagger_2.12_1.0/

Therefore, adding it to `plugins.sbt` doesn't work:

```text
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.iheart:sbt-play-swagger:0.10.6-PLAY2.8 (sbtVersion=1.0, scalaVersion=2.13)
[warn]
```

**Comment by kailuowang** [comment]
I have the impression that scala 1.x only runs on scala 2.12? But I haven't been following it closely.  Sb-play-swagger was never updated to support 2.13. but if you are interested, PR will be much appreciated

**Comment by denisftw** [comment]
Ah, I believe you're right! It seems that SBT plugins are different from other dependencies.

I think I found the cause of the problem. 

I had the previous version of the plugin in `plugins.sbt`:

```scala
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.10.4-PLAY2.8")
```
 
So, after added `SwaggerPlugin` to `build.sbt` it tried to download the `play-swagger` dependency (the library, not the plugin), and failed since it was never published. After updating the plugin to `0.10.6` it started working.

Thanks for a quick response!

This issue can be closed.
