### ISSUE TITLE
Wrong format for schema entity

### ISSUE THREAD

**Issue by Driox** [iheartradio/play-swagger#41]
Hello, 

I have a basic form, 

```
 case class SearchForm(name: Option[String], city: Option[String], limit: Option[Int], offset: Option[Int])
```

it's referenced in routes like that

```
### 
#  parameters:
#    - name: body
#      schema:
#        $ref: '#/definitions/models.entities.SearchForm'
###
```

the generated json is 

```
"models.entities.SearchForm":{  
         "properties":{  
            "name":{  
               "type":"string",
               "required":false
            },
            "city":{  
               "type":"string",
               "required":false
            },
            "limit":{  
               "type":"integer",
               "format":"int32",
               "required":false
            },
            "offset":{  
               "type":"integer",
               "format":"int32",
               "required":false
            }
         },
         "required":[  ]
      }
```

The swagger validator (http://online.swagger.io/validator/debug?url=http://your-json-url) tell me that 
- the "required":false should not exist
- "required":[  ] should not be empty.

**Comment by kailuowang** [comment]
Thanks for reporting these errors. I was aware of them but since they don't affect the final swagger UI result I forgot to log them. The issue is that in our code, we use the same model to represent both fields in schemas and fields in endpoints, but the json representation of required field is different in these two types of fields. Our code ended up producing json for both format, which can certainly be improved.

**Comment by Driox** [comment]
Thanks for the quick answer

It don't affect the swagger UI but the validation badge will be in error and that may be harmful for a public API.

**Comment by metasim** [comment]
I'm getting validation errors too, which is a concern as I plan on generating cross-language bindings against the API, and anything out of spec is a liability.

**Comment by kailuowang** [comment]
@metasim  we have the same plan on "generating cross-language bindings against the API" as well,  so we also need to a) fix this bug and b) add swagger validator. Any contribution will be much appreciated.

**Comment by kailuowang** [comment]
I think this is already fixed thanks to https://github.com/iheartradio/play-swagger/pull/78, please help test.
