### ISSUE TITLE
Custom model schema definition

### ISSUE THREAD

**Issue by AmirKarimi** [iheartradio/play-swagger#42]
When generating model schema for third-party types like `org.joda.time.Datetime` play-swagger generates the data-type correctly but it won't show up in Model Schema (JSON preview) in Swagger-UI.

Is it possible to define these types in somewhere like `swagger.yml`.

There are other situation which we need to define our type description manually. For example suppose the following object:

```scala
object ProgressStatus {
  type Type = String

  val Done = "done"
  val InPorgress = "inProgress"
}
```

Which we used like an Enumeration:

```scala
case class MyModel(status: ProgressStatus.Type)
```

I want to define `ProgressStatus.Type` manually and describe about it's valid values.

**Comment by kailuowang** [comment]
Right now play-swagger use run-time reflection to parse classes. For your case, did "string" show up as the data-type for your status? 
You might have to override the whole model schema for `MyModel` generated by play-swagger for in the swagger.yml, and provide another schema for `ProgressStatus` which then can be referenced by `MyModel`'s schema
