### ISSUE TITLE
Swagger doesn't recognized 'bigdecimal' type in generated definitions

### ISSUE THREAD

**Issue by carlsonngo** [iheartradio/play-swagger#43]
In SwaggerParameterMapper:

Add mapping from 'BigDecimal' as type 'number'

**Comment by kailuowang** [comment]
Since you already found where the mapper is, doesn't it look like a fairly easy change? Wanna give it a try? I promise I will release right after the merge. :)

**Comment by kailuowang** [comment]
fixed by https://github.com/iheartradio/play-swagger/pull/44
