### ISSUE TITLE
Does it work with play-java?

### ISSUE THREAD

**Issue by iAmcR** [iheartradio/play-swagger#46]
Hello, 

This is very good work. Does this work with Play-Java?

I ask because I notice the use of case classes for the definitions... 

Thank you.

**Comment by kailuowang** [comment]
it relies on runtime reflection on the default constructor. So if you have every field declared in the constructor it might work, but I haven't tested it. If you give it a try please let me know how it goes. Thanks

**Comment by ando--io** [comment]
hi,
it does work. the generated doc is almost fine. the only issue is with the schema and $ref. there is no primary constructor in java. So the objects definition is empty in the generated json.

**Comment by kailuowang** [comment]
@ando--io thanks for the note.

**Comment by jstnlef** [comment]
Is there a plan or any work going into making this work for Java as well? If not, I will probably look into it.

**Comment by kailuowang** [comment]
@jstnlef , the iheartradio team doesn't have such plan. Your contribution would be greatly appreciated.

**Comment by jstnlef** [comment]
Thanks 👍

**Comment by luben93** [comment]
hi
im trying to get this to work, and i get different models every time

**Comment by luben93** [comment]
#193
