### ISSUE TITLE
using argonaut serialisation?

### ISSUE THREAD

**Issue by Ir1sh** [iheartradio/play-swagger#47]
If we use argonaut as our json library are we out of luck with automatic schema generation or is there a way to make the plugin aware of that?

**Comment by kailuowang** [comment]
The automatically schema generation doesn't care about your json serialization implementation. It simply makes the assumption that your json field names are the same as your case class field names. 
The downside is that if you have a custom json schema play-swagger won't be able to derive automatic swagger schema for you. However, you should be able to override certain fields generated by play-swagger by defining, in swagger.yml, a schema with the same name but only the overriding fields.

**Comment by Ir1sh** [comment]
hmm maybe I am writing my route file comments wrong as I get "path.to.case.class is not defined" in the play-swagger output, I assumed it was because it couldn't serialise, I will try again, thanks
