### ISSUE TITLE
How to request a release?

### ISSUE THREAD

**Issue by Javakky-pxv** [iheartradio/play-swagger#470]
@kailuowang 
Thanks for your help.
I recently merged some features into the PLAY2.8 branch, how can I reach out to you to ask for a release?
We will probably ask you to work on releases periodically in the future and would like to determine the best way to contact you so that you are most aware of them.

**Comment by kailuowang** [comment]
@ me here usually reaches me. If not feel free to email me. I can do a release soon.. let me know.

**Comment by Javakky-pxv** [comment]
@kailuowang 
Thank you!
#481 would be nice to have you too 🙇
