### ISSUE TITLE
Which PLAY versions must be supported?

### ISSUE THREAD

**Issue by Javakky-pxv** [iheartradio/play-swagger#479]
@kailuowang 
To be honest, my product environment is running on Scala 2.13 + PLAY 2.8, so I personally have no motivation to support other versions.
However, looking at the README, it seems to support PLAY 2.4 or later.
As for iheartradio / play-swagger, to which version do we need to support?

example: 
https://github.com/iheartradio/play-swagger/issues/247
https://github.com/iheartradio/play-swagger/issues/259

**Comment by kailuowang** [comment]
The master branch support 2.7 while the 2.8 branch support 2.8. I think it's probably about time to drop 2.7 support by merging 2.8 into master.

**Comment by Javakky-pxv** [comment]
@kailuowang 
Thank you!
If support for other versions is needed, I'm sure that request issue will be raised, and we will consider the PLAY2.7 branch at that time.
(We will cut support for 2.7 for the time being.)
