### ISSUE TITLE
$ref generates -Xlint warnings

### ISSUE THREAD

**Issue by mikquinlan** [iheartradio/play-swagger#49]
It is valid to have a build fail on warnings, especially those generated by -Xlint.

However, $ref generates a warning and we either then have to:
- turn off missing-parameter, e.g. -Xlint:missing-parameter OR
- remove -Xfatal-warnings

Can we move to a different mechanism of determining references to classes or model types? Happy to contribute if you agree.

Thanks

**Comment by kailuowang** [comment]
can you post the warning generated? I know there is one it generates that gets fixed (or was getting fixed) by play.

**Comment by mikquinlan** [comment]
Here you go:

```[warn] /.../src/main/resources/api.routes:22: possible missing interpolator: detected interpolated identifier `$ref````

**Comment by kailuowang** [comment]
This should have been fixed https://github.com/playframework/playframework/issues/5134
try upgrade your play to 2.4.4+?

**Comment by mikquinlan** [comment]
Hi 

Thanks for referencing the issue. The fix is in version 2.5.0-M1 and greater.

We can't quite move to that version yet. :-(

I'll close the issue.

Mik

**Comment by kailuowang** [comment]
@mikquinlan also noticed that you can do `-Xlint:-warn-missing-interpolator`

**Comment by mikquinlan** [comment]
Unfortunately that is not a valid Xlint arg in Scala 2.11.7 :-(
