### ISSUE TITLE
Skip routes w/ no Swagger Spec comment

### ISSUE THREAD

**Issue by nVitius** [iheartradio/play-swagger#543]
I'm adding swagger comments to routes in my project as I need them.
The auto-generated ones that have no responses defined for them are not really useful to me at all (also, in the OpenAPI 3.x spec `operation.responses` is a required field). It would be nice if I could skip any routes that don't have comments on them. 

Not sure if this setting exists (I couldn't find it). I'd be happy to implement it if someone can point me in the right direction.

**Comment by Javakky-pxv** [comment]
@nVitius 
Perhaps the following features might be available.

> # How to hide an endpoint?
> If you don't want an end point to be included, add ### NoDocs ### in front of it e.g.
> 
> ```
> ### NoDocs ###
> GET   /docs/swagger-ui/*file        controllers.Assets.at(path:String="/public/lib/swagger-ui", file:String)
> ```
> 
> # Skip entire file
> The entire file can be skipped by adding `### SkipFileForDocs ###` at the beginning of the routes file.
> 
> Alternatively, the routes file can be split into multiple files, so that you can skip practically only a part of the file.
> 
> https://www.playframework.com/documentation/ja/2.4.x/SBTSubProjects
> 
> ```
> ### SkipFileForDocs ###
> 
> GET      /api/hidden/a                 controllers.hiddenEndPointA()
> GET      /api/hidden/b                 controllers.hiddenEndPointB()
> GET      /api/hidden/c                 controllers.hiddenEndPointC()
> ```

It may also be possible to create a feature here to skip blank comments in the SwaggerSpecGenerator.

https://github.com/iheartradio/play-swagger/blob/5ea8f16d76ebdf33a5e04bf705d1328b00c74f2f/core/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala#L416-L430

Sorry for the brief answer, but if you have any questions, please feel free to ask again.
