### ISSUE TITLE
Play 2.5 support

### ISSUE THREAD

**Issue by russwyte** [iheartradio/play-swagger#56]
Things seems to break with Play 2.5 at runtime:

java.lang.NoSuchMethodError: play.api.libs.json.JsLookup$.$bslash$extension(Lplay/api/libs/json/JsLookupResult;Ljava/lang/String;)Lplay/api/libs/json/JsLookupResult;
     com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$32.apply(SwaggerSpecGenerator.scala:292)
     com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$32.apply(SwaggerSpecGenerator.scala:292)
     scala.Option.flatMap(Option.scala:171)
     com.iheart.playSwagger.SwaggerSpecGenerator.endPointSpec(SwaggerSpecGenerator.scala:292)

**Comment by kailuowang** [comment]
released a 0.2.1-PLAY2.5 that is compatible.

**Comment by russwyte** [comment]
I wonder if simply factoring out the provided play-json lib would be a reasonable thing to do to promote wider compatibility across versions.

**Comment by kailuowang** [comment]
probably not a very straightfoward thing.

**Comment by russwyte** [comment]
Sure - I just wonder if there is a way to avoid the pain of named branch releases - perhaps not worth it.
