### ISSUE TITLE
[Urgent] Deployment Failures of This Repository Since April.

### ISSUE THREAD

**Issue by Javakky-pxv** [iheartradio/play-swagger#597]
@kailuowang 

It appears that the deployment of this repository has been failing since around April this year.

I've contemplated and applied various strategies to resolve this issue, including [updating](https://github.com/sbt/sbt-ci-release/releases/tag/v1.5.12) and [downgrading](https://github.com/sbt/sbt-ci-release/releases/tag/v1.5.7) sbt-ci-release, incorporating [decodekey.sh](https://eed3si9n.com/ja/auto-publish-sbt-plugin-from-github-actions/), and utilizing [setup-java](https://github.com/actions/setup-java). Regrettably, none of these methods have been successful.

A plausible cause for these errors could be the expiration of the GPG-Key. Your attention to confirm this would be greatly appreciated.

Here are the associated error logs for your reference:

```bash
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --batch --yes --pinentry-mode loopback --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/play-swagger/play-swagger/core/target/scala-2.12/play-swagger_2.12-1.1.10.pom.asc /home/runner/work/play-swagger/play-swagger/core/target/scala-2.12/play-swagger_2.12-1.1.10.pom'.  Exit code: 2
```

**Comment by Javakky-pxv** [comment]
Hello, @joprice .
I am @Javakky-pxv, the current maintainer of the play-swagger project.

I am considering transitioning this repository from com.iheart. I was wondering if you are still using this plugin?

Also, I am thinking of taking over as the owner in my domain.
Would you be interested in becoming the new owner of the repository, or do you have the motivation to participate in future development?

**Comment by Javakky-pxv** [comment]
@kailuowang 

The following has been migrated to the below repository.
https://github.com/play-swagger/play-swagger

The groupId for Maven Central has also been added.
```sbt
addSbtPlugin("io.github.play-swagger" % "sbt-play-swagger" % "1.2.3")
```

**Comment by kailuowang** [comment]
Awesome news! Thanks so much for the hard work.
