### ISSUE TITLE
Remove Swagger Json from Public Folder

### ISSUE THREAD

**Issue by Pixel2203** [iheartradio/play-swagger#605]
Hey there,
I was wondering if there is any way to remove the swagger.json from my target/web/public/main folder.
I dont want the swagger.json to be exposed to everyone. How can I achieve this ?
I tried setting swaggerTarget to another path, but it firstly generates it to the said directory and then additionally copies the swagger json also to the public folder. I did not find any option to change this, if you know anything, please let me know.

That's my swagger.yml

---
swagger: "2.0"
info:
  title: "Find"
  description: "Find everything!"
  version: "1.0.0"
consumes:
  - application/json
produces:
  - application/json

Regards 

Marvin

**Comment by Javakky-pxv** [comment]
@Pixel2203 
We will deal with the rest here.
https://github.com/play-swagger/play-swagger/issues/22
