### ISSUE TITLE
Getting "null" in response definition

### ISSUE THREAD

**Issue by phunsberger** [iheartradio/play-swagger#66]
First, great project, many thanks for your work!

In my routes I have comments as follows:

>   description: get the default module description
>   summary: default module
>   responses:
>   200:
>       description: success
>       schema:
>           $ref: '#/definitions/models.Protocol.ModuleDef'

(#'s removed to keep formatting sort of normal)

In the resultant swagger.json I get:

`"/":{
         "get":{
            "tags":[
               "routes"
            ],
            "summary":"default module",
            "description":"get the default module description",
            "responses":null,
            "200":{
               "description":"Modules definition",
               "schema":{
                  "$ref":"#/definitions/models.Protocol.ModuleDef"
               }
            },....`

Note the "null" instead of the JSON object start for the response.  The object that is being referenced is included in the definitions so it's not a case of a broken reference. 

I'm running Play 2.5 but get the same result with 2.4.6.  Build is using 0.2.0 not the 0.2.1 Play 2.5 specific version since that is currently throwing JSLookup errors when I try to use it instead.

**Comment by phunsberger** [comment]
The indent looks like what I would expect.  The formatting (leading spaces) seems to get lost when you cut and paste here?

**Comment by phunsberger** [comment]
Ack, found the problem, there was a tab embedded in the indenting.  Other portions of the same routes file have resulted in exceptions being thrown when tabs were embedded, that would likely be the better option here also?

**Comment by kailuowang** [comment]
we will add swagger validation in the future
