### ISSUE TITLE
Parse definitions in route files

### ISSUE THREAD

**Issue by herbakamil** [iheartradio/play-swagger#67]
It would be nice to parse definitions in route files in the form like below:

`###`
`#  definitions:`
`#    LoginRequest:`
`#      type: object`
`#      required:`
`#        - certificate`
`#      properties:`
`#        certificate:`
`#          $ref: '#/definitions/Certificate'`
`#    LoginResponse:`
`#      type: object`
`#      required:`
`#        - token`
`#      properties:`
`#        token:`
`#          $ref: '#/definitions/Token'`
play-swagger is being used also in Java projects where we don't have case classes so it'd be nice to allow definitions parsing.

Do you plan to support it? If yes when?

**Comment by kailuowang** [comment]
for anything that play-swagger doesn't provide, you can write it in the swagger.yml file. The core team doesn't have plan to write java class parsing any time soon but any contribution is more than welcome.

**Comment by herbakamil** [comment]
Thank you for the quick response :)

-- 
Kamil Herba
