### ISSUE TITLE
Generate YAML

### ISSUE THREAD

**Issue by guizmaii** [iheartradio/play-swagger#68]
Is it possible to generate YAML instead of JSON ?

**Comment by kailuowang** [comment]
I am curious what's the motivation for that?

**Comment by bestcastor** [comment]
Hi, the same question here. 
It seems we can only generate swagger.json, not swagger.yaml right?

**Comment by RESTful-web-dev** [comment]
Hi,

I really would be interested into that as well.

Any update on that ?

**Comment by Javakky-pxv** [comment]
@RESTful-web-dev 
I'll look at it while I'm on vacation, just hang on.
If you can create a PR for us, I promise to review it right away.
