### ISSUE TITLE
Optional query parameters do not show up correctly in the ui

### ISSUE THREAD

**Issue by joprice** [iheartradio/play-swagger#72]
Optional query parameters generated 'undefined' for their type, and 'None' as the default value. An example route that has this problem:

``` scala
GET /test  controllers.Controller.method(param: Option[String] ?= None)
```

**Comment by kailuowang** [comment]
This is probably a bug. but for this particular case, if I remember correctly, `param: Option[String]` is already a param with default value None, i.e. you don't need the `?= None` part.
