### ISSUE TITLE
Can it use the defined Reads and Writes for Json generation

### ISSUE THREAD

**Issue by prithvi23** [iheartradio/play-swagger#75]
1. The json that is emitted out is actually not matching the custom Writes that has been defined. I'm not sure if the play Formats are being used for Json generation
2. The Json generation fails for the class Consumer below as it uses the trait.

sealed trait ValueType
object Mobile extends ValueType

case class Consumer(root: String, users: Map[String, User], valueType: ValueType = Mobile)

**Comment by kailuowang** [comment]
@prithvi23 currently it's using reflection to get the fields. It doesn't support using a custom Reads or Writes. If you think about it, to use a custom reads and writes, you will need to provide not only the reads/writes and also an instance of the class, which will probably be more complex to write than just writing the schema in the swagger.yml. 
For the error case you provided, did the generation fails with a runtime exception or doe it just fail to provide a valid schema?

**Comment by prithvi23** [comment]
Can the Formats be used as an implicit?

[NoSuchElementException: None.get] 
This is the error that I get at the time of generation. 

Its failing at line number 19

def specs = cached("swaggerDef") {
18    Action.async { _ =>
19      Future.fromTry(generator.generate()).map(Ok(_))
20    }
21

**Comment by prithvi23** [comment]
Also Just would like to thank you for a good utility and a prompt response. :)

**Comment by kailuowang** [comment]
Looks like you are trying to encode an ADT, that is basically an enum. play-swagger doesn't support generating swagger doc for this type of data yet, (although it shouldn't throw a runtime exception). The best work around again is to write your schema definition in swagger.yml yourself ( don't $ref your Consumer class)

**Comment by prithvi23** [comment]
That would be nice - can you point me to a sample Swagger.yml file that overrides the definitions?
I also would need to generate custom definitions like List of consumer objects as Consumers etc...

**Comment by kailuowang** [comment]
you should be able to find plenty here. 
http://editor.swagger.io/#/
