### ISSUE TITLE
Enhancement: Allow defining path/query-bound datatypes

### ISSUE THREAD

**Issue by SattaiLanfear** [iheartradio/play-swagger#83]
Several of my endpoints take nontrivial datatypes in from the route file, for example `BSONObjectID`.

I know that type is a string with a particular pattern and length, and could define it, but when swagger-generator encounters it it uses the illegal type value "bsonobjectid".

As a first-step, assuming string for unknown types may be better than an illegal value.

**Comment by kailuowang** [comment]
I am not sure how I feel about assuming string for unknown types. The fact that it's an illegal type value makes it easier to call for attention. The original design was that in case like this you would have to override it in your swagger comment, like what you are trying to do in #82 
Would that approach work for you (assuming #82 is fixed)?  Or you can think of a smarter design (maybe plays-wagger automatically detects refs to unknown types like this, basically if you have a schema, the unknown type should be a '$ref'?)
