### ISSUE TITLE
Let's talk about 1.0 release

### ISSUE THREAD

**Issue by kailuowang** [iheartradio/play-swagger#84]
Please list issues here that we should address before an 1.0 release
cc @joprice @lvauthrin @williamho @mwalden @avpatel257

**Comment by kailuowang** [comment]
Here is a couple of issues I saw

1. Array "items" gets "type" even if "items" contains a manual $ref  #82  
2. default tag "routes" is confusing  #70  
3. Routes with multiple regexes #23 
4. support OpenAPI #39

**Comment by joprice** [comment]
Macro-based compilation. I have this working elsewhere and could contribute it.

**Comment by landsman** [comment]
is OpenAPI supported now?

**Comment by kailuowang** [comment]
Yes

**Comment by Javakky-pxv** [comment]
Due to the extended period of time that has passed, version 1.0 has been released as a temporary measure.
Several issues raised here will be reconsidered for version 2.0. Thank you very much !
