### ISSUE TITLE
sbt / build support to generate static swagger json

### ISSUE THREAD

**Issue by mosche** [iheartradio/play-swagger#90]
Hey,
thanks a lot for this project! Absolutely the approach I like best so far as it reduces the coupling between swagger and the actual play app :)

I looked a bit into the open PR using macros at compile time and was wondering if you are still looking into compile time generation? Generating a static swagger doc without having any runtime dependency would be great to have. 

An easier way could be to include a small runnable main class in the artifact and leverage that from sbt. Below is a quick & dirty example how to get it it integrated. However, going that way, it may make sense to turn the project into a multi-project build and build an sbt-plugin with it. I'm happy to work on a PR, but was wondering what your thoughts / preferences are?

Regards, Moritz

```scala
object Swagger extends App {
  implicit def cl = getClass.getClassLoader

  private def fileArg = Paths.get(args.head)
  private def domainNameSpaceArgs = args.tail
  private def swaggerJson = SwaggerSpecGenerator(domainNameSpaceArgs: _*).generate().get.toString

  Files.write(fileArg, swaggerJson.getBytes, StandardOpenOption.CREATE, StandardOpenOption.WRITE)
}
```
And finally generating the swagger.json from sbt and packaging it using a Plugin:
```scala
object SwaggerPlugin extends AutoPlugin {
  private[this] val swaggerConfig = config("play-swagger").hide

  object autoImport extends SwaggerKeys

  override def requires = PlayScala

  override def trigger = noTrigger

  import autoImport._

  override def projectSettings: Seq[Setting[_]] = Seq(
    ivyConfigurations += swaggerConfig,
    libraryDependencies += "com.iheart" %% "play-swagger" % "0.3.3-SNAPSHOT" % swaggerConfig,
    swaggerDomainNameSpaces := Seq(),
    swaggerTarget := "public/swagger.json",
    swagger <<= Def.task[File] {
      (target.value / "swagger").mkdirs()
      val file = target.value / "swagger" / "swagger.json"
      val args = file.absolutePath +: swaggerDomainNameSpaces.value
      val swaggerClasspath = data((fullClasspath in Runtime).value) ++ update.value.select(configurationFilter(swaggerConfig.name))
      runner.value.run("swagger.Swagger", swaggerClasspath, args, streams.value.log)
      file
    },
    mappings in (Compile, packageBin) += (target.value / "swagger" / "swagger.json") -> swaggerTarget.value,
    packageBin in Universal <<= (packageBin in Universal).dependsOn(swagger)
  )
}

trait SwaggerKeys {
  val swagger = TaskKey[File]("swagger", "generate the swagger API documentation")
  val swaggerDomainNameSpaces = SettingKey[Seq[String]]("swaggerDomainNameSpaces", "swagger domain namespaces for model classes")
  val swaggerTarget = SettingKey[String]("swaggerTarget", "the location of the swagger documentation")
}
```

**Comment by mtrovo** [comment]
Hey @mosche did you manage to make this auto plugin work?
I tried to adapt and use it here but couldn't get play-swagger dependencies to play well as a sbt-plugin as it uses scala 2.10.

**Comment by kailuowang** [comment]
@mosche I apologize for the late response, somehow I missed the notification. I like that idea would love to see a PR. Wdyt @joprice ?

**Comment by joprice** [comment]
I like this idea. After hitting the issues mentioned in the macro pr, I planned on trying this method next.

**Comment by mosche** [comment]
@mtrovo I was initially struggling with the 2.10/2.11dependency problem as well. The solution ended up being to run the 2.11 code using the sbt runner, therefore the main class.
I'll try and look into this again Friday or Monday.

**Comment by kailuowang** [comment]
@moshe yes @joprice and I had a discussion, we think runner might solve the 2.11 problem too. Thanks very much!

**Comment by kailuowang** [comment]
fixed by #97 thanks again @mosche

**Comment by kailuowang** [comment]
The plugin is available on bintray now. 
should be able to use it through
```Scala
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.4.1")
```

**Comment by mosche** [comment]
awesome :)
