### ISSUE TITLE
How to turn off validation in Swagger UI?

### ISSUE THREAD

**Issue by vasily-kirichenko** [iheartradio/play-swagger#92]
![image](https://cloud.githubusercontent.com/assets/873919/17211842/573282e2-54d4-11e6-93b5-e6d611ae493d.png)

```json
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://<private host name>:9000/docs/swagger.json"}]}
```

**Comment by kailuowang** [comment]
Is your swagger spec showing up? This error message swagger UI gave isn't very helpful 😞

**Comment by kbedel** [comment]
The validator badge in Swagger UI uses the publicly hosted version of the swagger validator. If you want to update it to either turn off the badge or point to a locally hosted validator which is able to reach your endpoint, you can set the validatorUrl property in the Swagger UI index.html page. See the Swagger UI [github page](https://github.com/swagger-api/swagger-ui) for more info.

If you are using docker to host your swagger UI endpoint, see [this docker hub image](https://hub.docker.com/r/schickling/swagger-ui/). I recently made a contribution that allows you to override the validator within the image.

**Comment by KamakshaiahM** [comment]
Hi, My case is little different , I am using Swagger UI Webjars-3.14.2 to generate Swagger UI JS files in my project structure dynamically, as a result if i introduce index.html file with validateURL:null attribute, the original from web jars retains back every time upon mvn compile. Could you put me in right direction.
