### ISSUE TITLE
how to define a list schema using case class

### ISSUE THREAD

**Issue by dragonly** [iheartradio/play-swagger#98]
I want to define a schema $ref using case class like this
```JavaScript
[
  {"key": "value"},
  ...
]
```
where I defined a case class for the key-value pair like
```Scala
case class keyVal(key: String)
```
but I cannot figure out how to define a case class to generate the above definitions, because it will end up with something like this
```JavaScript
{
  "whateverFieldName": [
    {"key": "value"},
    ...
  ]
}
```
because it seems i can only define it like
```Scala
case class ListOfKeyVal(List[KeyVal])
```

**Comment by kailuowang** [comment]
you might have to define the schema manually and ref it.

**Comment by dragonly** [comment]
got it. sad but thx
